ZSH_THEME="powerlevel9k/powerlevel9k"

# general powerlevel settings
POWERLEVEL9K_COLOR_SCHEME='dark'
POWERLEVEL9K_MODE='nerdfont-complete'
#POWERLEVEL9K_MODE='awesome-fontconfig'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user dir vcs virtualenv)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

# vcs segment settings
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='white'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='28'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='white'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='01'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='white'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='9'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='\uF103'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='\uF102'

# user segment settings
POWERLEVEL9K_USER_DEFAULT_FOREGROUND='white'
POWERLEVEL9K_USER_DEFAULT_BACKGROUND='black'
POWERLEVEL9K_USER_DEFAULT_VISUAL_IDENTIFIER_COLOR='226'
POWERLEVEL9K_USER_ICON="\uF17c"

# dir segment settings
POWERLEVEL9K_HOME_ICON='\uf015'
POWERLEVEL9K_HOME_SUB_ICON='\uF07c'
POWERLEVEL9K_FOLDER_ICON='\uF07c'
POWERLEVEL9K_ETC_ICON='\uf013'


